### ISSUE TITLE
Stryker throws java.util.NoSuchElementException in SBT 1.7.1

### ISSUE THREAD

**Issue by wmeints** [stryker-mutator/stryker4s#1222]
### Summary

I'm trying to run stryker on my ETL job written against Spark 3.2.2.
Stryker throws the following exception in SBT 1.7.1:

```
[error] java.util.NoSuchElementException: None.get
[error]         at scala.None$.get(Option.scala:529)
[error]         at scala.None$.get(Option.scala:527)
[error]         at stryker4s.sbt.runner.SocketTestRunnerConnection.$anonfun$sendMessage$5(TestRunnerConnection.scala:22
[error]         at unsafeRunSync @ stryker4s.sbt.Stryker4sMain$.$anonfun$strykerTask$1(Stryker4sMain.scala:55)
[error]         at joinWithNever @ fs2.Stream$NestedStreamOps$.$anonfun$parJoin$44(Stream.scala:4054)
[error]         at flatMap @ stryker4s.sbt.runner.SocketTestRunnerConnection.skipCancel(TestRunnerConnection.scala:31)
[error]         at map @ stryker4s.sbt.runner.SocketTestRunnerConnection.sendMessage(TestRunnerConnection.scala:22)
[error]         at map @ stryker4s.sbt.runner.SocketTestRunnerConnection.sendMessage(TestRunnerConnection.scala:23)
[error]         at flatTap @ stryker4s.mutants.Mutator.mutate(Mutator.scala:37)
[error]         at unsafeRunSync @ stryker4s.sbt.Stryker4sMain$.$anonfun$strykerTask$1(Stryker4sMain.scala:55)
[error]         at joinWithNever @ fs2.Stream$NestedStreamOps$.$anonfun$parJoin$44(Stream.scala:4054)
[error]         at flatMap @ stryker4s.sbt.runner.SocketTestRunnerConnection.skipCancel(TestRunnerConnection.scala:31)
[error]         at apply @ stryker4s.sbt.runner.SocketTestRunnerConnection.sendMessage(TestRunnerConnection.scala:19)
[error] (stryker) java.util.NoSuchElementException: None.get
```

### Stryker4s config

```hocon
stryker4s {
    reporters = ["html", "console"]
    scala-dialect = "2.12"
}
```

### Stryker4s environment

```
stryker4s 0.14.3
```

### Your Environment
| software                | version(s) |
| -------------------- | ---------- |
| Scala version        | 2.12.15 |
| Build tool & version | sbt 1.7.1 | 
| Operating System     | Windows 11 22H2 |

**Comment by hugo-vrijswijk** [comment]
Closing this as the test-runner has been majorly reworked and I don't believe this is an issue anymore
