### ISSUE TITLE
HTML reporter throws exception when running SBT plugin

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker4s#178]
### Summary

Running the sbt plugin with the HTML reporter enabled will give the below stacktrace at the end of the mutation run. This does not happen with the Maven plugin or inside tests (yay)
```log
11:29:20.890 [pool-7-thread-1] INFO  stryker4s.report.ConsoleReporter - Finished mutation run 1/1 (100%)
[error] java.util.NoSuchElementException: Could not find resource=META-INF/resources/webjars/mutation-testing-elements/1.0.2/dist/mutation-test-elements.js
[error]         at better.files.Resource$.notFound(Resource.scala:110)
[error]         at better.files.Resource.$anonfun$getAsString$1(Resource.scala:68)
[error]         at scala.Option.getOrElse(Option.scala:121)
[error]         at better.files.Resource.getAsString(Resource.scala:68)
[error]         at better.files.Resource.getAsString$(Resource.scala:62)
[error]         at better.files.Resource$.getAsString(Resource.scala:106)
[error]         at stryker4s.files.DiskFileIO$.readResource(fileIO.scala:16)
[error]         at stryker4s.report.HtmlReporter.indexHtml(HtmlReporter.scala:20)
[error]         at stryker4s.report.HtmlReporter.reportRunFinished(HtmlReporter.scala:40)
[error]         at stryker4s.report.Reporter.$anonfun$reportRunFinished$1(Reporter.scala:26)
[error]         at stryker4s.report.Reporter.$anonfun$reportRunFinished$1$adapted(Reporter.scala:26)
[error]         at scala.collection.immutable.List.foreach(List.scala:388)
[error]         at stryker4s.report.Reporter.reportRunFinished(Reporter.scala:26)
[error]         at stryker4s.run.MutantRunner.apply(MutantRunner.scala:41)
[error]         at stryker4s.Stryker4s.run(Stryker4s.scala:20)
[error]         at stryker4s.run.Stryker4sRunner.run(Stryker4sRunner.scala:31)
[error]         at stryker4s.run.Stryker4sRunner.run$(Stryker4sRunner.scala:17)
[error]         at stryker4s.sbt.Stryker4sSbtRunner.run(Stryker4sSbtRunner.scala:16)
[error]         at stryker4s.sbt.Stryker4sPlugin$.$anonfun$strykerTask$1(Stryker4sPlugin.scala:37)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (stryker) java.util.NoSuchElementException: Could not find resource=META-INF/resources/webjars/mutation-testing-elements/1.0.2/dist/mutation-test-elements.js
```
### Stryker4s config

```conf
stryker4s {
  reporters: ["html", "console"]
}
```

### Stryker4s environment

```
stryker4s 0.3.1
```

### Your Environment
| software             | version(s) |
| -------------------- | ---------- |
| Scala version        |      2.12.8      |
| Build tool & version |      sbt 1.2.8      | 
| Operating System     |      Both Windows and WSL      |

**Comment by nicojs** [comment]
What happened? 🤓

**Comment by hugo-vrijswijk** [comment]
Who knows. My feeling is that sbt is doing some classpath/classloader/dependency magic that (re)moves the resource
