### ISSUE TITLE
Failed to add mutation(s) to new mutated code

### ISSUE THREAD

**Issue by tanyagorn** [stryker-mutator/stryker4s#902]
### Summary

```
[warn] Failed to add mutation(s) 54 to new mutated code
[warn] The code that failed to mutate was: [Future
[warn]       .successful(validatorScheme.invoke())
[warn]       .flatMap { validation =>
[warn]         if (validation) {
[warn]           block
[warn]         } else {
[warn]           executeDefaultForFuture(default, s"validation failed for $msg")
[warn]         }
[warn]       }
[warn]       .recoverWith { case NonFatal(t) =>
[warn]         val errorMsg = s"Error performing $msg due to ${t.getMessage}"
[warn]         validatorScheme.loggerFunc(errorMsg, logger, exception = t)
[warn]         executeDefaultForFuture(default, errorMsg)
[warn]       }] at Input.File(new File("/Users/tb/dummy.scala"), Charset.forName("UTF-8")):40:5
[warn] This mutation will likely show up as Survived
[warn] Please open an issue on github with sample code of the mutation that failed: https://github.com/stryker-mutator/stryker4s/issues/new
```

After multiple warning of failed to add mutation (above is only one of them). Finally I got [ERROR] and Stryker stop running

```
[error] java.lang.StackOverflowError
[error] 	at scala.meta.transversers.Transformer.apply(Transformer.scala:4)
[error] 	at stryker4s.extension.TreeExtensions$TransformOnceExtension$OnceTransformer.super$apply(TreeExtensions.scala:97)
[error] 	at stryker4s.extension.TreeExtensions$TransformOnceExtension$OnceTransformer.$anonfun$apply$1(TreeExtensions.scala:97)
[error] 	at stryker4s.mutants.applymutants.MatchBuilder$$anonfun$1.applyOrElse(MatchBuilder.scala:20)
[error] 	at stryker4s.mutants.applymutants.MatchBuilder$$anonfun$1.applyOrElse(MatchBuilder.scala:20)
[error] 	at stryker4s.extension.TreeExtensions$TransformOnceExtension$OnceTransformer.apply(TreeExtensions.scala:97)
[error] 	at scala.meta.transversers.Transformer.apply(Transformer.scala:4)
[error] 	at stryker4s.extension.TreeExtensions$TransformOnceExtension$OnceTransformer.super$apply(TreeExtensions.scala:97)
[error] 	at stryker4s.extension.TreeExtensions$TransformOnceExtension$OnceTransformer.$anonfun$apply$1(TreeExtensions.scala:97)
[error] 	at stryker4s.mutants.applymutants.MatchBuilder$$anonfun$1.applyOrElse(MatchBuilder.scala:20)

```
### Stryker4s config

```
Using default config
```

### Stryker4s environment

```
stryker4s 0.12.1
```

### Your Environment
| software             | version(s) |
| -------------------- | ---------- |
| Scala version        |       2.12.12     |
| Build tool & version |     Intellij Idea community 2021.1.3 (community edition)       | 
| Operating System     |     macOS       |

**Comment by hugo-vrijswijk** [comment]
Fixed in 0.15.0
