### ISSUE TITLE
Error  java.lang.NoSuchMethodError: java.nio.file.Files.readString at the end of mutation run

### ISSUE THREAD

**Issue by gowthamraj198** [stryker-mutator/stryker4s#934]
### 
In the new version of stryker4s 0.13.0, at the end of test run (possibly while creating reports) there is an error thrown and the test run fails. 

`  java.lang.NoSuchMethodError: java.nio.file.Files.readString(Ljava/nio/file/Path;)Ljava/lang/String;
    at stryker4s.report.mapper.MutantRunResultMapper.fileContentAsString(MutantRunResultMapper.scala:68)
    at stryker4s.report.mapper.MutantRunResultMapper.toFileResult(MutantRunResultMapper.scala:35)
    at stryker4s.report.mapper.MutantRunResultMapper.$anonfun$toFileResultMap$1(MutantRunResultMapper.scala:28)
    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
    at scala.collection.immutable.NewRedBlackTree$._foreach(RedBlackTree.scala:283)
    at scala.collection.immutable.NewRedBlackTree$._foreach(RedBlackTree.scala:282)
    at scala.collection.immutable.NewRedBlackTree$._foreach(RedBlackTree.scala:282)
    at scala.collection.immutable.NewRedBlackTree$._foreach(RedBlackTree.scala:282)
    at scala.collection.immutable.NewRedBlackTree$._foreach(RedBlackTree.scala:282)
    at scala.collection.immutable.NewRedBlackTree$.foreach(RedBlackTree.scala:260) `

### Stryker4s config

```  stryker4s {
           base-dir: "test"
           mutate: [
                ,"app/**/*.scala"
           ]
           test-filter : [
                 "!*config.*"
           ]
           reporters: ["console", "html"]
           scala-dialect: "2.12"
           excluded-mutations: ["StringLiteral"]
           concurrency: 2
           timeout: 50000
   } ```

```
stryker4s 0.13.0
```

### Your Environment
| software             | version(s) |
| -------------------- | ---------- |
| Scala version        |      2.13      |
| Build tool & version |     sbt       | 
| Operating System     |            |

**Comment by gowthamraj198** [comment]
https://github.com/stryker-mutator/stryker4s/pull/929/files#diff-01ff57452388d82342abf549dbc370c2638d18dd7d90857dfb4a3a8ef87c596cR68

this could be the issue!
