### ISSUE TITLE
XIncludeAwareParserConfiguration cannot be cast to class XMLParserConfiguration

### ISSUE THREAD

**Issue by tanyagorn** [stryker-mutator/stryker4s#941]
### Summary

Not sure that is this related with the latest fix version or not, but I got this error when hit run stryker for a subproject.

```
[error] (subproject / update) java.lang.ClassCastException: class org.apache.xerces.parsers.XIncludeAwareParserConfiguration cannot be cast to class org.apache.xerces.xni.parser.XMLParserConfiguration (org.apache.xerces.parsers.XIncludeAwareParserConfiguration is in unnamed module of loader sbt.internal.PluginManagement$PluginClassLoader @5e4ebc15; org.apache.xerces.xni.parser.XMLParserConfiguration is in unnamed module of loader sbt.internal.PluginManagement$PluginClassLoader @20f6f88c)
[error] stack trace is suppressed; run last stryker for the full output
[error] (stryker) stryker4s.extension.exception.TestSetupException: Could not setup mutation testing environment. Unable to resolve project classpath. This could be due to compile errors or misconfiguration of Stryker4s. See debug logs for more information.
```

Then I run last stryker to see debug log and got this ...

```
[debug] testrunner 13337: Test unsuccessful: null status Failure with OptionalThrowable(java.lang.ExceptionInInitializerError)
[debug] testrunner 13337: Fatal exception reported by testrunner. Re-throwing java.lang.ExceptionInInitializerError
[debug] testrunner 13337: Exception in thread "main" java.lang.ExceptionInInitializerError
[debug] testrunner 13337:       at org.mockito.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:167)
[debug] testrunner 13337:       at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
[debug] testrunner 13337:       at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
[debug] testrunner 13337:       at org.mockito.cglib.core.KeyFactory$Generator.create(KeyFactory.java:145)
[debug] testrunner 13337:       at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:117)
[debug] testrunner 13337:       at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:109)
[debug] testrunner 13337:       at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:105)
[debug] testrunner 13337:       at org.mockito.cglib.proxy.Enhancer.<clinit>(Enhancer.java:70)
[debug] testrunner 13337:       at org.mockito.internal.creation.jmock.ClassImposterizer.createProxyClass(ClassImposterizer.java:85)
[debug] testrunner 13337:       at org.mockito.internal.creation.jmock.ClassImposterizer.imposterise(ClassImposterizer.java:62)
[debug] testrunner 13337:       at org.mockito.internal.creation.jmock.ClassImposterizer.imposterise(ClassImposterizer.java:56)
[debug] testrunner 13337:       at org.mockito.internal.creation.CglibMockMaker.createMock(CglibMockMaker.java:23)
[debug] testrunner 13337:       at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:26)
[debug] testrunner 13337:       at org.mockito.internal.MockitoCore.mock(MockitoCore.java:51)
[debug] testrunner 13337:       at org.mockito.Mockito.mock(Mockito.java:1243)
[debug] testrunner 13337:       at org.mockito.Mockito.mock(Mockito.java:1120)
[debug] testrunner 13337:       at org.scalatestplus.mockito.MockitoSugar.mock(MockitoSugar.scala:73)
[debug] testrunner 13337:       at org.scalatestplus.mockito.MockitoSugar.mock$(MockitoSugar.scala:72)
[debug] testrunner 13337:       at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[debug] testrunner 13337:       at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[debug] testrunner 13337:       at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[debug] testrunner 13337:       at org.scalatest.Transformer.apply(Transformer.scala:22)
[debug] testrunner 13337:       at org.scalatest.Transformer.apply(Transformer.scala:20)
[debug] testrunner 13337:       at org.scalatest.FlatSpecLike$$anon$5.apply(FlatSpecLike.scala:1682)
[debug] testrunner 13337:       at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[debug] testrunner 13337:       at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[debug] testrunner 13337:       at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
[debug] testrunner 13337:       at org.scalatest.FlatSpecLike.invokeWithFixture$1(FlatSpecLike.scala:1680)
[debug] testrunner 13337:       at org.scalatest.FlatSpecLike.$anonfun$runTest$1(FlatSpecLike.scala:1692)
[debug] testrunner 13337:       at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
[debug] Closing test-runner on port 13337
[debug] testrunner 13337:       at org.scalatest.FlatSpecLike.runTest(FlatSpecLike.scala:1692)
[debug] testrunner 13337:       at org.scalatest.FlatSpecLike.runTest$(FlatSpecLike.scala:1674)
[error] java.io.EOFException
[error]         at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2960)
[error]         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1540)
[error]         at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
[error]         at stryker4s.sbt.runner.SocketTestRunnerConnection.$anonfun$sendMessage$4(TestRunnerConnection.scala:21)
[error]         at blocking @ stryker4s.sbt.runner.SocketTestRunnerConnection.sendMessage(TestRunnerConnection.scala:21)
[error] (stryker) java.io.EOFException
```

Any idea of what's going on here?

### Stryker4s config

```
 stryker4s {
     base-dir: "subproject"
     reporters: ["console", "html", "json"]
     excluded-mutations: [ "StringLiteral" ]
     mutate: [
          "src/main/scala/**/*.scala"
     ]

     max-test-runner-reuse: 0
     concurrency: 1
 }
```

### Stryker4s environment

```
stryker4s 0.13.1
```

### Your Environment
| software             | version(s) |
| -------------------- | ---------- |
| Scala version        |     2.12.12       |
| Build tool & version |     IntelliJ IDEA CE 2021.1.3      | 
| Operating System     |     MacOS       |

**Comment by hugo-vrijswijk** [comment]
Closing due to inactivity
